add_agent_id: True
add_last_action:  True
agent_num:  3
batch_size: 32
buffer_size: 5120
best_store_nums:  5
epsilon: 1.0
epsilon_decay_steps:  100000
epsilon_min:  0.1
device: cuda
evaluate_freq: 5000
evaluate_times: 3
gamma:  0.99
hidden_dim: 64
hyper_hidden_dim: 64
hyper_layers_num: 2
lambda: 0.95
learning_rate:  0.0005
max_episode_times:  25
max_train_steps: 800000
Qmix_hidden_dim:  64
result_path:  'result'
reward_path:  './data_train/QMIX_rewards.npy'
rnn_hidden_dim: 64
target_update_frequence:  100
target_update_theta:  0.008
train_log_intervals:  100
train_times_per_episode: 3
testing_episode:  5
update_epoches: 5
use_adv_norm: True
use_hard_update:  False
use_grad_clip: True
use_orthogonal_init:  True
use_reward_norm:  False
use_rnn:  True