agent_num:  3
batch_size: 32
best_store_nums:  5
clip_epsilon: 0.2
device: cuda
entropy_coef: 0.01
episode_times: 30
evaluate_freq: 5000
evaluate_times: 3
gamma:  0.99
hidden_dim: 64
lambda: 0.95
learning_rate:  0.0005
max_episode_times:  30
max_train_steps: 1500000
mini_batch_size:  8
result_path:  'result'
reward_path:  './data_train/MAPPO_rewards.npy'
train_log_intervals:  100
train_times_per_episode: 20
testing_episode:  5
update_epoches: 5
use_adv_norm: True
use_grad_clip: True
use_orthogonal_init:  True
use_reward_norm:  True