device: cuda
learning_rate: 0.001
buffer_lenth: 10000
batch_size: 64
gamma:  0.99
epsilon:  0.1
update_frequence:  100
epsilon_start:  1
epsilon_end:  0.01
epsilon_decay:  0.995
lr: 0.01
embed_dim:  128
episode:  500
actor_lr: 0.0003
critic_lr: 0.001
frame_num:  5
warmup_episodes: 40