_allow_no_value:
    value: false
_comment_prefixes:
    value:
        - '#'
        - ;
_converters:
    value: <configparser.ConverterMapping object at 0x7691350f6c90>
_defaults:
    value:
        actionprob: "0.25"
        clipgradnorm: "0.5"
        entropy: "0.001"
        envid: MontezumaRevengeNoFrameskip-v4
        envtype: atari
        epoch: "4"
        extcoef: "2."
        gamma: "0.999"
        intcoef: "1."
        intgamma: "0.99"
        lambda: "0.95"
        learningrate: "1e-4"
        lifedone: "False"
        maxstepperepisode: "4500"
        minibatch: "4"
        numenv: "128"
        numstep: "128"
        obsnormstep: "50"
        ppoeps: "0.1"
        preprocheight: "84"
        proprocwidth: "84"
        stableeps: "1e-8"
        statestacksize: "4"
        stickyaction: "True"
        trainmethod: RND
        updateproportion: "0.25"
        usegae: "True"
        usegpu: "True"
        usenoisynet: "False"
        usenorm: "False"
_delimiters:
    value:
        - =
        - ':'
_dict:
    value: builtins.dict
_empty_lines_in_values:
    value: true
_inline_comment_prefixes:
    value: []
_interpolation:
    value: <configparser.BasicInterpolation object at 0x76907ac9a1b0>
_optcre:
    value: 're.compile(''\n        (?P<option>.*?)                    # very permissive!\n        \\s*(?P<vi>=|:)\\s*              # any number of space/tab,\n                                           # followed by any of t, re.VERBOSE)'
_proxies:
    value:
        DEFAULT: '<Section: DEFAULT>'
        OPTIONS: '<Section: OPTIONS>'
_sections:
    value:
        OPTIONS:
            envtype: '[atari]'
_strict:
    value: true
_wandb:
    value:
        cli_version: 0.19.11
        m:
            - "1": data/reward_per_epi
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": sample_episode
              "6": []
              "7": []
            - "1": data/int_reward_per_epi
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": data/max_prob
              "5": 2
              "6":
                - 1
                - 3
              "7": []
            - "1": data/reward_per_rollout
              "5": 6
              "6":
                - 1
                - 3
              "7": []
            - "1": global_update
              "6": []
              "7": []
            - "1": data/int_reward_per_rollout
              "5": 6
              "6":
                - 1
                - 3
              "7": []
        python_version: 3.12.4
        t:
            "1":
                - 1
                - 55
            "2":
                - 1
                - 55
            "3":
                - 7
                - 13
                - 16
                - 23
                - 55
            "4": 3.12.4
            "5": 0.19.11
            "8":
                - 6
            "10":
                - 20
            "12": 0.19.11
            "13": linux-x86_64
default_section:
    value: DEFAULT
